### ISSUE TITLE
Tracking: MVP checklist

### ISSUE THREAD

**Issue by hopeyen** [graphops/file-hosting-service#17]
This issue should track all the items needed for a minimal viable product. 

More updated details can be found in Feature_checklist.md.

### General 
- [x] Standarlise subfile/chunkfile manifest formats https://github.com/graphops/subfile-data-service/issues/2
- [ ] Draft out GRC https://github.com/graphops/subfile-data-service/issues/25
- [x] Better naming https://github.com/graphops/subfile-data-service/issues/18

### User experience
- [x] Dataset Discovery on a marketplace
  - [x] File Discovery and matching across datasets https://github.com/graphops/subfile-data-service/issues/19
    - [x] Search Functionality
  - [x] Dataset Listing from server
- [x] Matching Algorithm https://github.com/graphops/subfile-data-service/issues/21
  - [ ] User Preference Analysis (price per byte, response rate)
  - [ ] Transaction History Utilization

### Subfile transfer 
- [ ] work with Horizon for data service interfaces
- [x] Server
  - [x] port into indexer-service framework (should take care of TAP receipt handling)
  - [x] add cost model scheme, allow updates for pricing per byte https://github.com/graphops/subfile-data-service/issues/20
- [x] Use generic path to be compatible with cloud storages https://github.com/graphops/subfile-data-service/issues/15

### Subfile Client
- [ ] Verifiable Payment https://github.com/graphops/subfile-data-service/issues/21
  - [x] Take private key/mneomic for wallet connections
  - [x] take budget for the overall subfile
    - [x] construct receipts using budget and chunk sizes
    - [x] add receipt to request
- [x] Parallelize requests https://github.com/graphops/subfile-data-service/issues/16
- [x] Multiple connections (HTTPS over HTTP2)
- [x] Continually requesting missing pieces until the complete file is obtained https://github.com/graphops/subfile-data-service/issues/22

### Testing and Deployment
- [x] Service custom errors https://github.com/graphops/subfile-data-service/issues/23
- [x] Track metrics https://github.com/graphops/subfile-data-service/issues/24
- [x] Track code test coverage
- [ ] Deployment Planning 
  - [x] Add deployment options (docker + binary)
  - [ ] Internal Infrastructure Support 
  - [ ] Reach out to key users for early feedbacks
- [ ] Documentation and Support
  - [ ] Support System Setup (Channel)
  - [x] Tutorials, FAQs

Beyong MVP scope
- Multiple hashing options/scheme; Taking file sizes and number of files, analyze performance and memory of using merkle tree vs hash list
